export { JOB_TITLES } from "@/lib/seo/job-titles";

export const SKILLS_TECH_OPTIONS = [
  "Java",
  "C++",
  "C#",
  "Python",
  "JavaScript",
  "TypeScript",
  "React",
  "Vue",
  "Angular",
  "Node.js",
  "SQL",
  "AWS",
  "Docker",
  "Kubernetes",
  "Go",
  "Rust",
  ".NET",
  "PHP",
  "Swift",
  "Kotlin",
  "React Native",
  "Flutter",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "GraphQL",
  "REST API",
  "Git",
  "Linux",
  "Agile",
  "Scrum",
] as const;

export const WORK_TRAIT_OPTIONS = [
  "Communication",
  "Leadership",
  "Problem solving",
  "Teamwork",
  "Time management",
  "Adaptability",
  "Attention to detail",
  "Self-motivation",
] as const;
